name: Create Pipeline

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy Dev
        working-directory: /home/retivate/reti-backend
        run: |
          set -e
          git pull origin dev
          npm ci --legacy-peer-deps
          npm run build
          pm2 restart retivate-backend --update-env || pm2 start dist/main.js --name retivate-backend
          pm2 save
