name: Create Pipeline

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy Dev
        run: |
          cd ~/reti-backend
          git pull origin dev
          npm ci
          npm run build
          pm2 restart retivate-backend --update-env